[locuszoom]
file = /project/voightlab_01/lorenzk/Romberg_eQTL/Allergy_coloc/plots/looping_plots/inputs/ZBTB10_TFH_LD0.bedgraph
file_type = bedgraph
type = points:8
color = #00008B
use_middle = true
height = 5
min_value = 0
max_value = 12
title = Tfh ZBTB10 eQTL

[locuszoom]
file = /project/voightlab_01/lorenzk/Romberg_eQTL/Allergy_coloc/plots/looping_plots/inputs/ZBTB10_TFH_LD.2.bedgraph
file_type = bedgraph
type = points:8
color = #87CEEB
use_middle = true
height = 5
min_value = 0
max_value = 12
overlay_previous = yes

[locuszoom]
file = /project/voightlab_01/lorenzk/Romberg_eQTL/Allergy_coloc/plots/looping_plots/inputs/ZBTB10_TFH_LD.4.bedgraph
file_type = bedgraph
type = points:8
color = #006400
use_middle = true
height = 5
min_value = 0
max_value = 12
overlay_previous = yes

[locuszoom]
file = /project/voightlab_01/lorenzk/Romberg_eQTL/Allergy_coloc/plots/looping_plots/inputs/ZBTB10_TFH_LD.6.bedgraph
file_type = bedgraph
type = points:8
color = #FFA500
use_middle = true
height = 5
min_value = 0
max_value = 12
overlay_previous = yes

[locuszoom]
file = /project/voightlab_01/lorenzk/Romberg_eQTL/Allergy_coloc/plots/looping_plots/inputs/ZBTB10_TFH_LD.8.bedgraph
file_type = bedgraph
type = points:8
color = #FF0000
use_middle = true
height = 5
min_value = 0
max_value = 12
overlay_previous = yes

[locuszoom]
file = /project/voightlab_01/lorenzk/Romberg_eQTL/Allergy_coloc/plots/looping_plots/inputs/ZBTB10_TFH_label.bedgraph
file_type = bedgraph
type = points:8
color = #A020F0
use_middle = true
height = 5
min_value = 0
max_value = 12
overlay_previous = yes


[spacer]

[locuszoom]
file = /project/voightlab_01/lorenzk/Romberg_eQTL/Allergy_coloc/plots/looping_plots/inputs/ZBTB10_pAsthma_LD0.bedgraph
file_type = bedgraph
type = points:8
color = #00008B
use_middle = true
height = 5
min_value = 0
max_value = 19
title = pAsthma GWAS

[locuszoom]
file = /project/voightlab_01/lorenzk/Romberg_eQTL/Allergy_coloc/plots/looping_plots/inputs/ZBTB10_pAsthma_LD.2.bedgraph
file_type = bedgraph
type = points:8
color = #87CEEB
use_middle = true
height = 5
min_value = 0
max_value = 19
overlay_previous = yes

[locuszoom]
file = /project/voightlab_01/lorenzk/Romberg_eQTL/Allergy_coloc/plots/looping_plots/inputs/ZBTB10_pAsthma_LD.4.bedgraph
file_type = bedgraph
type = points:8
color = #006400
use_middle = true
height = 5
min_value = 0
max_value = 19
overlay_previous = yes

[locuszoom]
file = /project/voightlab_01/lorenzk/Romberg_eQTL/Allergy_coloc/plots/looping_plots/inputs/ZBTB10_pAsthma_LD.6.bedgraph
file_type = bedgraph
type = points:8
color = #FFA500
use_middle = true
height = 5
min_value = 0
max_value = 19
overlay_previous = yes

[locuszoom]
file = /project/voightlab_01/lorenzk/Romberg_eQTL/Allergy_coloc/plots/looping_plots/inputs/ZBTB10_pAsthma_LD.8.bedgraph
file_type = bedgraph
type = points:8
color = #FF0000
use_middle = true
height = 5
min_value = 0
max_value = 19
overlay_previous = yes

[locuszoom]
file = /project/voightlab_01/lorenzk/Romberg_eQTL/Allergy_coloc/plots/looping_plots/inputs/ZBTB10_pAsthma_label.bedgraph
file_type = bedgraph
type = points:8
color = #A020F0
use_middle = true
height = 5
min_value = 0
max_value = 19
overlay_previous = yes
[spacer]

[bigwig]
file = /project/voightlab_01/lorenzk/Romberg_eQTL/ATAC_CaptureC_Pahl/NaiveB_fc.signal_hg38.bigwig
color = blue
height = 3
title = Naive B ATAC

[spacer]

[bigwig]
file = /project/voightlab_01/lorenzk/Romberg_eQTL/ATAC_CaptureC_Pahl/GCB_fc.signal_hg38.bigwig
color = green
height = 3
title = G CB ATAC

[spacer]

[bigwig]
file = /project/voightlab_01/lorenzk/Romberg_eQTL/ATAC_CaptureC_Pahl/NaiveT_fc.signal_hg38.bigwig
color = purple
height = 3
title = Naive T ATAC

[spacer]

[bigwig]
file = /project/voightlab_01/lorenzk/Romberg_eQTL/ATAC_CaptureC_Pahl/TFH_fc.signal_hg38.bigwig
color = orange
height = 3
title = Tfh ATAC

[spacer]

[arcs]
file = /project/voightlab_01/lorenzk/Romberg_eQTL/ATAC_CaptureC_Pahl/NaiveB/NaiveB_CaptureC_hg38.bedpe
color = blue
line_width = 1
height = 4
title = Naive B Capture C

[spacer]

[arcs]
file = /project/voightlab_01/lorenzk/Romberg_eQTL/ATAC_CaptureC_Pahl/GCB/GCB_CaptureC_hg38.bedpe
color = green
line_width = 1
height = 4
title = GC B       Capture C

[spacer]

[arcs]
file = /project/voightlab_01/lorenzk/Romberg_eQTL/ATAC_CaptureC_Pahl/NaiveT/NaiveT_CaptureC_hg38.bedpe
color = purple
line_width = 1
height = 4
title = Naive T Capture C

[spacer]

[arcs]
file = /project/voightlab_01/lorenzk/Romberg_eQTL/ATAC_CaptureC_Pahl/TFH/TFH_CaptureC_hg38.bedpe
color = orange
line_width = 1
height = 4
title = Tfh       Capture C

[spacer]

[genes]
file = /project/voightlab_01/lorenzk/Romberg_eQTL/reference_files/gencode.v34.annotation.gtf
height = 3
fontsize = 22
file_type = gtf
prefered_name = gene_name
merge_transcripts = TRUE
labels_in_margin = TRUE
style: UCSC


[x-axis]
fontsize=20

[vlines]
file = /project/voightlab_01/lorenzk/Romberg_eQTL/Allergy_coloc/plots/looping_plots/inputs/lead_snps_ZBTB10_TFH_forlooping.bed
type = vlines
line_width = 1
#line_style = 'dashed'
alpha = 0.7


[vhighlight]
file = /project/voightlab_01/lorenzk/Romberg_eQTL/tensorqtl/ABF/ZBTB10_TFH_abf_credset_bounds.bed
type = vhighlight
color = lightgrey
alpha = 0.2




